apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: hotel-auth-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: FLASK_ENV
              value: "production"
            - name: SQLALCHEMY_DATABASE_URI
              value: "sqlite:////data/auth.db"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: hotel-secrets
                  key: JWT_SECRET_KEY
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hotel-secrets
                  key: ADMIN_USERNAME
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: hotel-secrets
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hotel-secrets
                  key: ADMIN_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: auth-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: hotel
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 5001
      targetPort: 5001
