apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: bookings
          image: hotel-booking-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: FLASK_ENV
              value: "production"
            - name: SQLALCHEMY_DATABASE_URI
              value: "sqlite:////data/bookings.db"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: hotel-secrets
                  key: JWT_SECRET_KEY
            - name: ROOMS_BASE_URL
              value: "http://room-service:5002"
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5003
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5003
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bookings-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: hotel
spec:
  selector:
    app: booking-service
  ports:
    - name: http
      port: 5003
      targetPort: 5003
