apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: hotel
data:
  AUTH_URL: "http://auth-service:5001"
  ROOM_URL: "http://room-service:5002"
  BOOKING_URL: "http://booking-service:5003"
